### ISSUE TITLE
CLIP/ Unable to find config files

### ISSUE THREAD

**Issue by msocko420** [modelscope/richdreamer#1]
Hello there. This project is incredible and truly ground breaking. I followed all the proper steps and received this error: mike@kash1w:~/RichDreamer$ python3 ./run_nerf.py -t a log cabin -o outputs -s 1
cmd:bash scripts/nerf/run_single.sh 0 "a" outputs 128 1
GPU: 0
ITER: 3000
guidance_type: none
a
a
output_dir: outputs
python sys path:['/home/mike/RichDreamer', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/mike/.local/lib/python3.10/site-packages', '/home/mike/taichi_3d_gaussian_splatting', '/home/mike/One-2-3-45/src/taming-transformers', '/home/mike/Gaus/GaussianDreamer/shap-e', '/home/mike/LucidDreamer/point-e', '/usr/local/lib/python3.10/dist-packages', '/usr/local/lib/python3.10/dist-packages/smplx-0.1.28-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/numpy-1.26.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/typing_extensions-4.8.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/triton-2.1.0-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/sympy-1.12-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nvtx_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nccl_cu12-2.18.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cusparse_cu12-12.1.0.106-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cusolver_cu12-11.4.5.107-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_curand_cu12-10.3.2.106-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cufft_cu12-11.0.2.54-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cudnn_cu12-8.9.2.26-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_runtime_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_nvrtc_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_cupti_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cublas_cu12-12.1.3.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/networkx-3.2-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/Jinja2-3.1.2-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/fsspec-2023.10.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/filelock-3.12.4-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/mpmath-1.3.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nvjitlink_cu12-12.3.52-py3.10-linux-x86_64.egg', '/home/mike/bitsandbytes', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages', '/tmp/tmpsqmqttaw', '/home/mike/RichDreamer/extern/nd_sd']
Global seed set to 0
[INFO] ================has_nd_guidanece:True, has_rgb_sd_guidanece:True=================
[INFO] Loading Stable Diffusion ...
Loading pipeline components...: 100%|████████████████████| 4/4 [00:00<00:00,  4.26it/s]
[INFO] Loaded Stable Diffusion!
[INFO] Using prompt [a] and negative prompt []
[INFO] Using view-dependent prompts [side]:[a, side view] [front]:[a, front view] [back]:[a, back view] [overhead]:[a, overhead view]
[INFO] Loading Multiview Diffusion ...
Loading model from config: configs/inference/nd/txtcond_mvsd-4-objaverse_finetune_wovae.yaml
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
kaiming initialize camera embedding weights!
kaiming initialize camera embedding weights!
/home/mike/.local/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: DeprecationWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", DeprecationWarning)
Traceback (most recent call last):
  File "/home/mike/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/RichDreamer/launch.py", line 104, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/mike/RichDreamer/threestudio/systems/base.py", line 41, in __init__
    self.configure()
  File "/home/mike/RichDreamer/threestudio/systems/nd_mvdream.py", line 46, in configure
    self.nd_guidance = threestudio.find(self.cfg.nd_guidance_type)(
  File "/home/mike/RichDreamer/threestudio/utils/base.py", line 101, in __init__
    self.configure(*args, **kwargs)
  File "/home/mike/RichDreamer/threestudio/models/guidance/nd_multiview_diffusion_guidance.py", line 58, in configure
    self.model, self.model_cfg = build_model(
  File "/home/mike/RichDreamer/extern/nd_sd/model_zoo.py", line 111, in build_model
    model = instantiate_from_config(config.model)
  File "/home/mike/RichDreamer/extern/nd_sd/ldm/util.py", line 116, in instantiate_from_config
    return get_obj_from_str(config['target'])(**config.get('params', dict()))
  File "/home/mike/RichDreamer/extern/nd_sd/ldm/interface.py", line 73, in __init__
    self.cond_stage_model = instantiate_from_config(cond_stage_config)
  File "/home/mike/RichDreamer/extern/nd_sd/ldm/util.py", line 116, in instantiate_from_config
    return get_obj_from_str(config['target'])(**config.get('params', dict()))
  File "/home/mike/RichDreamer/extern/nd_sd/ldm/modules/encoders/modules.py", line 183, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/home/mike/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2008, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
python sys path:['/home/mike/RichDreamer', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/mike/.local/lib/python3.10/site-packages', '/home/mike/taichi_3d_gaussian_splatting', '/home/mike/One-2-3-45/src/taming-transformers', '/home/mike/Gaus/GaussianDreamer/shap-e', '/home/mike/LucidDreamer/point-e', '/usr/local/lib/python3.10/dist-packages', '/usr/local/lib/python3.10/dist-packages/smplx-0.1.28-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/numpy-1.26.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/typing_extensions-4.8.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/triton-2.1.0-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/sympy-1.12-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nvtx_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nccl_cu12-2.18.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cusparse_cu12-12.1.0.106-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cusolver_cu12-11.4.5.107-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_curand_cu12-10.3.2.106-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cufft_cu12-11.0.2.54-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cudnn_cu12-8.9.2.26-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_runtime_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_nvrtc_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cuda_cupti_cu12-12.1.105-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_cublas_cu12-12.1.3.1-py3.10-linux-x86_64.egg', '/usr/local/lib/python3.10/dist-packages/networkx-3.2-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/Jinja2-3.1.2-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/fsspec-2023.10.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/filelock-3.12.4-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/mpmath-1.3.0-py3.10.egg', '/usr/local/lib/python3.10/dist-packages/nvidia_nvjitlink_cu12-12.3.52-py3.10-linux-x86_64.egg', '/home/mike/bitsandbytes', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages', '/tmp/tmp9cwvy16n', '/home/mike/RichDreamer/extern/nd_sd']
Global seed set to 0
[INFO] Initializing geometry from a given checkpoint ...
Traceback (most recent call last):
  File "/home/mike/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/RichDreamer/launch.py", line 104, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/mike/RichDreamer/threestudio/systems/base.py", line 41, in __init__
    self.configure()
  File "/home/mike/RichDreamer/threestudio/systems/nd_mvdream.py", line 26, in configure
    super().configure()
  File "/home/mike/RichDreamer/threestudio/systems/base.py", line 262, in configure
    prev_cfg = load_config(
  File "/home/mike/RichDreamer/threestudio/utils/config.py", line 102, in load_config
    yaml_confs = [OmegaConf.load(f) for f in yamls]
  File "/home/mike/RichDreamer/threestudio/utils/config.py", line 102, in <listcomp>
    yaml_confs = [OmegaConf.load(f) for f in yamls]
  File "/home/mike/.local/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/RichDreamer/outputs/tmp/nd-mv-nerf/geo-fast/a/configs/parsed.yaml'

is this due to me having a wrong version of a dependency or a user error on my end?

**Comment by gxd1994** [comment]
@msocko420 
Make sure you have the following models.
```bash
RichDreamer
|-- pretrained_models
    |-- Damo_XR_Lab
        |-- Normal-Depth-Diffusion-Model
            |-- nd_mv_ema.ckpt
            |-- albedo_mv_ema.ckpt
    
    |-- huggingface
        |-- hub
            |-- models--runwayml--stable-diffusion-v1-5
            |-- models--openai--clip-vit-large-patch14
            |-- models--stabilityai--stable-diffusion-2-1-base
            |-- models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K
```
`models--openai--clip-vit-large-patch14` and other SD or CLIP models can download  from [aliyun-link] (https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/RichDreamer/models_sd_clip.tar.gz)

**Or** you download via huggingface API and you need to set `TRANSFORMERS_OFFLINE=0 DIFFUSERS_OFFLINE=0 HF_HUB_OFFLINE=0` in `*.sh` and it will connect hugging face and automatic download models. 

Thank you for your discovery, we have updated README for clear  instruction

**Comment by gxd1994** [comment]
@msocko420 
one more thing, you need to add double quotes to the prompt.
python3 ./run_nerf.py -t "$prompt" -o $output

e.g.  python3 ./run_nerf.py -t "a log cabin" -o outputs -s 1

have fun! thanks

**Comment by msocko420** [comment]
Thank you for the quick response, i followed the instructions and properly downloaded and structured the files properly, but still had this issue: mike@kash1w:~/Deskto
p/RichDreamer$      pyth      pyth./run_
on3 ./run_nerf.py -t "a log cabin" -o outputs -s 1
cmd:bash scripts/nerf/run_single.sh 0 "a log cabin" outputs 128 1
GPU: 0
ITER: 3000
guidance_type:  none
input prompt: a log cabin
output_dir: outputs
Traceback (most recent call last):
  File "/home/mike/Desktop/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/Desktop/RichDreamer/launch.py", line 74, in main
    import threestudio
  File "/home/mike/Desktop/RichDreamer/threestudio/__init__.py", line 34, in <module>
    from . import data, models, systems
  File "/home/mike/Desktop/RichDreamer/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, dmtet_multiview, image, multiview, random_multiview, uncond
  File "/home/mike/Desktop/RichDreamer/threestudio/data/co3d.py", line 16, in <module>
    from threestudio.data.uncond import (RandomCameraDataModuleConfig,
  File "/home/mike/Desktop/RichDreamer/threestudio/data/uncond.py", line 12, in <module>
    from threestudio.utils.base import Updateable
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/base.py", line 6, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/misc.py", line 4, in <module>
    import tinycudann as tcnn
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mike/.local/lib/python3.10/site-packages/tinycudann_bindings/_89_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
Traceback (most recent call last):
  File "/home/mike/Desktop/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/Desktop/RichDreamer/launch.py", line 74, in main
    import threestudio
  File "/home/mike/Desktop/RichDreamer/threestudio/__init__.py", line 34, in <module>
    from . import data, models, systems
  File "/home/mike/Desktop/RichDreamer/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, dmtet_multiview, image, multiview, random_multiview, uncond
  File "/home/mike/Desktop/RichDreamer/threestudio/data/co3d.py", line 16, in <module>
    from threestudio.data.uncond import (RandomCameraDataModuleConfig,
  File "/home/mike/Desktop/RichDreamer/threestudio/data/uncond.py", line 12, in <module>
    from threestudio.utils.base import Updateable
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/base.py", line 6, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/misc.py", line 4, in <module>
    import tinycudann as tcnn
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mike/.local/lib/python3.10/site-packages/tinycudann_bindings/_89_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
Traceback (most recent call last):
  File "/home/mike/Desktop/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/Desktop/RichDreamer/launch.py", line 74, in main
    import threestudio
  File "/home/mike/Desktop/RichDreamer/threestudio/__init__.py", line 34, in <module>
    from . import data, models, systems
  File "/home/mike/Desktop/RichDreamer/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, dmtet_multiview, image, multiview, random_multiview, uncond
  File "/home/mike/Desktop/RichDreamer/threestudio/data/co3d.py", line 16, in <module>
    from threestudio.data.uncond import (RandomCameraDataModuleConfig,
  File "/home/mike/Desktop/RichDreamer/threestudio/data/uncond.py", line 12, in <module>
    from threestudio.utils.base import Updateable
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/base.py", line 6, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/misc.py", line 4, in <module>
    import tinycudann as tcnn
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mike/.local/lib/python3.10/site-packages/tinycudann_bindings/_89_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
Traceback (most recent call last):
  File "/home/mike/Desktop/RichDreamer/launch.py", line 236, in <module>
    main(args, extras)
  File "/home/mike/Desktop/RichDreamer/launch.py", line 74, in main
    import threestudio
  File "/home/mike/Desktop/RichDreamer/threestudio/__init__.py", line 34, in <module>
    from . import data, models, systems
  File "/home/mike/Desktop/RichDreamer/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, dmtet_multiview, image, multiview, random_multiview, uncond
  File "/home/mike/Desktop/RichDreamer/threestudio/data/co3d.py", line 16, in <module>
    from threestudio.data.uncond import (RandomCameraDataModuleConfig,
  File "/home/mike/Desktop/RichDreamer/threestudio/data/uncond.py", line 12, in <module>
    from threestudio.utils.base import Updateable
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/base.py", line 6, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/mike/Desktop/RichDreamer/threestudio/utils/misc.py", line 4, in <module>
    import tinycudann as tcnn
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/mike/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/mike/.local/lib/python3.10/site-packages/tinycudann_bindings/_89_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
cp: cannot stat 'outputs/tmp/nd-mv-nerf/tex-fast/a_DSLR_photo_of_a_log_cabin/save/it3000-export/*': No such file or directory
time cost:15.390177011489868
mike@kash1w:~/Desktop/RichDreamer$ 

It seems the requirements.txt and requirements_3d.txt gives me fits as well. just looking to give feedback and help get this repo seamless. excited for this one!
